from django.http import HttpResponse
from django.shortcuts import render
import json
from .forms import BikeDetailForm


def index(request):
    bike_data = [
  {
    "Company": "OLA",
    "Name": "S1 Air",
    "Price": "119827Rs",
    "Range": "125Km",
    "Speed": "90kmph",
    "Weight": "108kg",
    "Time": "5Hrs",
    "Power": "2700W",
    "Height": "792mm",
    "Colors": "Red,Black,Yellow,Blue",
    "Max_Power": "4500W",
    "Warranty": "3 Year",
    "Length": "1859 mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/ola-select-model-coral-glam-1690531573444.jpg?q=80"
  },
  {
    "Company": "Bajaj",
    "Name": "Chetak",
    "Price": "128853Rs",
    "Range": "90Km",
    "Speed": "63Kmph",
    "Weight": "109Kg",
    "Time": "5Hrs",
    "Power": "3800W",
    "Height": "770mm",
    "Colors": "Black,Red,Dark Blue,Blue",
    "Max_Power": "4080W",
    "Warranty": "3 Year",
    "Length": "1890mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/bajaj-select-model-brooklyn-black-1578996768669.jpg?q=80"
  },
  {
    "Company": "TVS",
    "Name": "iQube",
    "Price": "131964Rs",
    "Range": "100Km",
    "Speed": "78Kmph",
    "Weight": "117Kg",
    "Time": "5Hrs",
    "Power": "3000W",
    "Height": "770mm",
    "Colors": "White,Yellow,Blue,Grey",
    "Max_Power": "4400W",
    "Warranty": "3 Year",
    "Length": "1805mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/tvs-select-model-titanium-grey-1653284633810.jpg?q=80"
  },
  {
    "Company": "OLA",
    "Name": "S1 Pro",
    "Price": "139828RS",
    "Range": "170Km",
    "Speed": "116Kmph",
    "Weight": "125Kg",
    "Time": "6.30Hrs",
    "Power": "5500W",
    "Height": "792mm",
    "Colors": "Silver,Blue,Black,Jet Black",
    "Max_Power": "8500W",
    "Warranty": "3 Year",
    "Length": "1859mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/642x361/n/cw/ec/107243/s1-pro-right-front-three-quarter-5.jpeg?isig=0"
  },
  {
    "Company": "Hero Electric",
    "Name": "Optima CX",
    "Price": "67329Rs",
    "Range": "82Km",
    "Speed": "42Kmph",
    "Weight": "72.5Kg",
    "Time": "5Hrs",
    "Power": "550W",
    "Height": "795mm",
    "Colors": "Red,Black,Yellow,Blue",
    "Max_Power": "1200W",
    "Warranty": "3 Year",
    "Length": "1900mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/hero-electric-select-model-red-1628875274054.jpg?q=80"
  },
  {
    "Company": "Ather",
    "Name": "450S",
    "Price": "129653Rs",
    "Range": "115Km",
    "Speed": "90Kmph",
    "Weight": "108Kg",
    "Time": "8.3Hrs",
    "Power": "5400W",
    "Height": "780mm",
    "Colors": "Green",
    "Max_Power": "5400W",
    "Warranty": "3 Year",
    "Length": "1890mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/ather-select-model-salt-green-1691740406322.png?q=80"
  },
  {
    "Company": "Simple Energy",
    "Name": "One",
    "Price": "145000Rs",
    "Range": "212Km",
    "Speed": "110Kmph",
    "Weight": "110Kg",
    "Time": "5Hrs",
    "Power": "4500W",
    "Height": "796mm",
    "Colors": "Red,Black,Grey",
    "Max_Power": "8500W",
    "Warranty": "3 Year",
    "Length": "1900mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/simple-energy-select-model-brazen-black-1635246310664.jpg?q=80"
  },
  {
    "Company": "Revolt",
    "Name": "RV 400",
    "Price": "134788Rs",
    "Range": "150Km",
    "Speed": "85Kmph",
    "Weight": "108Kg",
    "Time": "4.5Hrs",
    "Power": "3000W",
    "Height": "814mm",
    "Colors": "Red ,Black,White",
    "Max_Power": "3000W",
    "Warranty": "8 Year",
    "Length": "2156mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/revolt-select-model-rebel-red-1667196840642.jpg?q=80"
  },
  {
    "Company": "Ather",
    "Name": "450X Gen 3",
    "Price": "137376Rs",
    "Range": "111Km",
    "Speed": "90Kmph",
    "Weight": "108Kg",
    "Time": "8.36Hrs",
    "Power": "6400W",
    "Height": "780mm",
    "Colors": "Red,Black,Grey,White",
    "Max_Power": "6400W",
    "Warranty": "3 Year",
    "Length": "1891mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/272x153/n/cw/ec/147925/450x-left-front-three-quarter.jpeg?isig=0&q=80"
  },
  {
    "Company": "Joy e-bike",
    "Name": "Mihos",
    "Price": "148990Rs",
    "Range": "130Km",
    "Speed": "70Kmph",
    "Weight": "110Kg",
    "Time": "5Hrs",
    "Power": "1500W",
    "Height": "814mm",
    "Colors": "Blue,Yellow,White",
    "Max_Power": "1500W",
    "Warranty": "2 Year",
    "Length": "1890mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/joy-ebike-select-model-metallic-blue-1673875757111.jpg?q=80"
  },
  {
    "Company": "iVOOMi",
    "Name": "S1",
    "Price": "69999Rs",
    "Range": "80Km",
    "Speed": "55Kmph",
    "Weight": "100Kg",
    "Time": "5Hrs",
    "Power": "1550W",
    "Height": "796mm",
    "Colors": "Blue,white,Red,Grey",
    "Max_Power": "1200W",
    "Warranty": "2 Year",
    "Length": "1852mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/ivoomi-select-model-red-1663938382029.gif?q=80"
  },
  {
    "Company": "Odysse",
    "Name": "Evoqis",
    "Price": "171250Rs",
    "Range": "140Km",
    "Speed": "80Kmph",
    "Weight": "150Kg",
    "Time": "6Hrs",
    "Power": "3000W",
    "Height": "750mm",
    "Colors": "Red,Green,Black",
    "Max_Power": "3000W",
    "Warranty": "3 Year",
    "Length": "2060mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/odysse-select-model-cobalt-blue-1635507428425.jpg?q=80"
  },
  {
    "Company": "Yo Drift",
    "Name": "Yo Drift",
    "Price": "51094Rs",
    "Range": "60Km",
    "Speed": "25Kmph",
    "Weight": "59Kg",
    "Time": "8Hrs",
    "Power": "250W",
    "Height": "775mm",
    "Colors": "Red,Blue,Grey,Black",
    "Max_Power": "250W",
    "Warranty": "3 Year",
    "Length": "1810mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-black-1600710154877.jpg?q=80"
  },
  {
    "Company": "Evolet",
    "Name": "Evolet Pony",
    "Price": "41124Rs",
    "Range": "80Km",
    "Speed": "25Kmph",
    "Weight": "90Kg",
    "Time": "8Hrs",
    "Power": "250W",
    "Height": "800mm",
    "Colors": "Red,Blue,Grey,Black",
    "Max_Power": "350W",
    "Warranty": "3 Year",
    "Length": "1750mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/evolet-select-model-red-1567601975830.jpg?q=80"
  },
  {
    "Company": "Techo Electra",
    "Name": "Neo",
    "Price": "41919Rs",
    "Range": "60Km",
    "Speed": "25Kmph",
    "Weight": "51Kg",
    "Time": "5Hrs",
    "Power": "250W",
    "Height": "796mm",
    "Colors": "Lemon Green,Red,Grey",
    "Max_Power": "250W",
    "Warranty": "2 Year",
    "Length": "1670mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-red-1574424979454.jpg?q=80"
  },
  {
    "Company": "Vida",
    "Name": "Vida V1 Pro",
    "Price": "141746Rs",
    "Range": "110Km",
    "Speed": "80Kmph",
    "Weight": "125Kg",
    "Time": "8Hrs",
    "Power": "3900W",
    "Height": "780mm",
    "Colors": "Orange,Black,Red.Blue",
    "Max_Power": "6000W",
    "Warranty": "3 Year",
    "Length": "1914mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/vida-select-model-white-1686937068875.jpg?q=80"
  },
  {
    "Company": "PURE EV",
    "Name": "EPluto 7G",
    "Price": "86702Rs",
    "Range": "120Km",
    "Speed": "60Kmph",
    "Weight": "76Kg",
    "Time": "4Hrs",
    "Power": "1500W",
    "Height": "760mm",
    "Colors": "Blue,Grey,Yellow,White",
    "Max_Power": "2200W",
    "Warranty": "3 Year",
    "Length": "1345mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-ruby-red-1602248979285.jpg?q=80"
  },
  {
    "Company": "BGauss",
    "Name": "C12i",
    "Price": "126153Rs",
    "Range": "135Km",
    "Speed": "62Kmph",
    "Weight": "110Kg",
    "Time": "7Hrs",
    "Power": "1500W",
    "Height": "765mm",
    "Colors": "Yellow,Blue",
    "Max_Power": "2500W",
    "Warranty": "3 Year",
    "Length": "1825mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/bgauss-select-model-yellow-techno-1687868078509.png?q=80"
  },
  {
    "Company": "Benling",
    "Name": "Aura",
    "Price": "91667Rs",
    "Range": "120Km",
    "Speed": "60Kmph",
    "Weight": "100Kg",
    "Time": "6Hrs",
    "Power": "2500W",
    "Height": "780mm",
    "Colors": "Blue,Dark Blue,Black",
    "Max_Power": "2500W",
    "Warranty": "3 Year",
    "Length": "1855mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-glossy-blue-1603730412634.jpg?q=80"
  },
  {
    "Company": "Okinawa",
    "Name": "R30",
    "Price": "61534Rs",
    "Range": "60Km",
    "Speed": "25Kmph",
    "Weight": "90Kg",
    "Time": "5Hrs",
    "Power": "250W",
    "Height": "735mm",
    "Colors": "Orange,Yellow,Red",
    "Max_Power": "250W",
    "Warranty": "3 Year",
    "Length": "1725mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okinawa-select-model-cyan-1689754699797.png?q=80"
  },
  {
    "Company": "Matter AREA",
    "Name": "AREA 5000",
    "Price": "1,73,999 RS",
    "Range": "125 Km",
    "Speed": "85 Kmph",
    "Weight": "128 Kg",
    "Time": "5 Hrs",
    "Power": "250W",
    "Height": "789 mm",
    "Colors": "Black, Blue, Grey, Red",
    "Max_Power": "10,000 W",
    "Warranty": "3 Year",
    "Length": "1869 mm",
    "Touches": "Yes",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/137187/aera-right-front-three-quarter.jpeg?isig=0&q=80"
  },
  {
    "Company": "Techo Electra Raptor",
    "Name": "Raptor Standard",
    "Price": "57,893 RS",
    "Range": "90-100 Km",
    "Speed": "25 Kmph",
    "Weight": "60 Kg",
    "Time": "4-5 Hrs",
    "Power": "250 W",
    "Height": "700 mm",
    "Colors": "Red, Green, White, Black, Blue",
    "Max_Power": "250 W",
    "Warranty": "2 Year",
    "Length": "1930 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/techoelectra-raptor.jpg?20191906194925&q=80"
  },
  {
    "Company": "Tork Kratos",
    "Name": "Kratos Urban",
    "Price": "1,67,499 RS",
    "Range": "100 Km",
    "Speed": "70 Kmph",
    "Weight": "140 Kg",
    "Time": "6-7 Hrs",
    "Power": "4000 W",
    "Height": "785 mm",
    "Colors": "White, Navy Blue, Red, Black, Brown",
    "Max_Power": "9000 W",
    "Warranty": "3 Year",
    "Length": "1960 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/tork-select-model-white-1683624461366.jpg?q=80"
  },
  {
    "Company": "Okaya Faast F2F",
    "Name": "Faast F2F Standard",
    "Price": "99,950 RS",
    "Range": "80 Km",
    "Speed": "55 Kmph",
    "Weight": "65 Kg",
    "Time": "5 Hrs",
    "Power": "800 W",
    "Height": "770 mm",
    "Colors": "Green, Black, Silver, White, Grey",
    "Max_Power": "1200 W",
    "Warranty": "2 Year",
    "Length": "2040 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/142689/left-side-view.jpeg?isig=0&q=80"
  },
  {
    "Company": "Yo Edge",
    "Name": "Edge DX",
    "Price": "49,086 RS",
    "Range": "60 Km",
    "Speed": "25 Kmph",
    "Weight": "59 Kg",
    "Time": "7-8 Hrs",
    "Power": "250 W",
    "Height": "700 mm",
    "Colors": "Black, Blue, Pink, White",
    "Max_Power": "250 W",
    "Warranty": "3 Year",
    "Length": "1750 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-black-1600710183148.jpg?q=80"
  },
  {
    "Company": "Okinawa Praise",
    "Name": "Praise Pro",
    "Price": "90,282 RS",
    "Range": "88 Km",
    "Speed": "58 Kmph",
    "Weight": "70 Kg",
    "Time": "2-3 Hrs",
    "Power": "1000 W",
    "Height": "800 mm",
    "Colors": "Red,Navy Blue, Black, Orange, Green",
    "Max_Power": "2500 W",
    "Warranty": "3 Year",
    "Length": "1970 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okinawa-select-model-glossy-red-black-1689833960448.png?q=80"
  },
  {
    "Company": "Pure EV",
    "Name": "Etryst 350 Standard",
    "Price": "1,49,999 RS",
    "Range": "140 Km",
    "Speed": "85 Kmph",
    "Weight": "120 Kg",
    "Time": "6 Hrs",
    "Power": "3000 W",
    "Height": "770 mm",
    "Colors": "Blue, Black, Red",
    "Max_Power": "4000 W",
    "Warranty": "2 Year",
    "Length": "2040 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/pure-ev-select-model-sea-blue-1656072689588.jpg?q=80"
  },
  {
    "Company": "Ampere Magnus",
    "Name": "Magnus EX LI",
    "Price": "1,04,758 RS",
    "Range": "121 Km",
    "Speed": "53 Kmph",
    "Weight": "90 Kg",
    "Time": "6-7 Hrs",
    "Power": "1200 W",
    "Height": "780 mm",
    "Colors": "Red, Grey, Black",
    "Max_Power": "2100 W",
    "Warranty": "3 Year",
    "Length": "1920 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/pure-ev-select-model-sea-blue-1656072689588.jpg?q=80"
  },
  {
    "Company": "BGauss",
    "Name": "D15i",
    "Price": "1,34,257 RS",
    "Range": "115 Km",
    "Speed": "60 Kmph",
    "Weight": "107 Kg",
    "Time": "5.30 Hrs",
    "Power": "1500 W",
    "Height": "765 mm",
    "Colors": "Green, White, Red, Blue",
    "Max_Power": "3000 W",
    "Warranty": "3 Year",
    "Length": "1868 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-alpine-green-1655198533497.gif?q=80"
  },
  {
    "Company": "Odysse Vader",
    "Name": "Vader Standard",
    "Price": "1,09,999 RS",
    "Range": "125 Km",
    "Speed": "85 Kmph",
    "Weight": "128 Kg",
    "Time": "4 Hrs",
    "Power": "3000 W",
    "Height": "800 mm",
    "Colors": "Blue, Red, Black, Green, Grey",
    "Max_Power": "4500 W",
    "Warranty": "3 Year",
    "Length": "1345 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/odysse-select-model-midnight-blue-1680779169172.png?q=80"
  },
  {
    "Company": "Evolet Derby",
    "Name": "Derby EZ",
    "Price": "49,124 RS",
    "Range": "90-120 kM",
    "Speed": "25 Kmph",
    "Weight": "90 Kg",
    "Time": "8-9 Hrs",
    "Power": "250 W",
    "Height": "800 mm",
    "Colors": "White, Navy Blue, Red, Black, Brown",
    "Max_Power": "350 W",
    "Warranty": "3 Year",
    "Length": "1930 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/evolet-select-model-white-1567601948374.jpg?q=80"
  },
  {
    "Company": "Joy e-bike",
    "Name": "Glob Standard",
    "Price": "76,267 RS",
    "Range": "60 Km",
    "Speed": "25 Kmph",
    "Weight": "67 Kg",
    "Time": "4 Hrs",
    "Power": "250 W",
    "Height": "770 mm",
    "Colors": "Silver",
    "Max_Power": "250 W",
    "Warranty": "2 Year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-silver-1610359048505.jpg?q=80"
  },
  {
    "Company": "Ampere Primus",
    "Name": "Primus Standard",
    "Price": "1,45,862 RS",
    "Range": "107 Km",
    "Speed": "77 Kmph",
    "Weight": "130 Kg",
    "Time": "5 Hrs",
    "Power": "3400 W",
    "Height": "750 mm",
    "Colors": "Orange, Blue, White, Black",
    "Max_Power": "4000 W",
    "Warranty": "3 Year",
    "Length": "1912 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/ampere-select-model-royal-orange-1676634193693.png?q=80"
  },
  {
    "Company": "Bounce Infinity",
    "Name": "Infinity E1",
    "Price": "1,00,95 RS",
    "Range": "85 Km",
    "Speed": "65 Kmph",
    "Weight": "94 Kg",
    "Time": "4 Hrs",
    "Power": "1500 W",
    "Height": "780 mm",
    "Colors": "Black, Grey, Red, White",
    "Max_Power": "1500 W",
    "Warranty": "3 Year",
    "Length": "1820 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/bounce-select-model-sparkle-black-1638947542336.jpg?q=80"
  },
  {
    "Company": "Hero Electric",
    "Name": "Atria LX",
    "Price": "77,767 RS",
    "Range": "85 Km",
    "Speed": "25 Kmph",
    "Weight": "69 Kg",
    "Time": "4-5 Hrs",
    "Power": "250 W",
    "Height": "785 mm",
    "Colors": "Grey, Brown",
    "Max_Power": "250 W",
    "Warranty": "3 Year",
    "Length": "1750 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/hero-electric-select-model-grey-1620729264562.jpg?q=80"
  },
  {
    "Company": "Hero Electric",
    "Name": "NYX HX Dual Battery",
    "Price": "86,490 RS",
    "Range": "165 Km",
    "Speed": "42 Kmph",
    "Weight": "87 Kg",
    "Time": "4-5 Hrs",
    "Power": "600 W",
    "Height": "700 mm",
    "Colors": "Black. Grey",
    "Max_Power": "1300 W",
    "Warranty": "3 Year",
    "Length": "1920 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/hero-electric-select-model-black-1628868818503.jpg?q=80"
  },
  {
    "Company": "Okaya Freedum",
    "Name": "Freedum LI-2",
    "Price": "74,899 RS",
    "Range": "75 Km",
    "Speed": "25 Kmph",
    "Weight": "65 Kg",
    "Time": "5-6 Hrs",
    "Power": "250 W",
    "Height": "745 mm",
    "Colors": "Black, Grey, Blue, Green",
    "Max_Power": "250 W",
    "Warranty": "3 Year",
    "Length": "2010 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okaya-select-model-black-1663138128892.jpg?q=80"
  },
  {
    "Company": "Pure EV",
    "Name": "ETrance Neo Standard",
    "Price": "81,959 RS",
    "Range": "120 Km",
    "Speed": "60 Kmph",
    "Weight": "86 Kg",
    "Time": "4 Hrs",
    "Power": "1500 W",
    "Height": "800 mm",
    "Colors": "White, Brown, Dark Blue, Black",
    "Max_Power": "2200 W",
    "Warranty": "3 Year",
    "Length": "1345 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/pure-ev-select-model-white-1615888506163.jpg?q=80"
  },
  {
    "Company": "Okaya",
    "Name": "Faast F3 Standard",
    "Price": "1,24,990 RS",
    "Range": "130 Km",
    "Speed": "70 Kmph",
    "Weight": "125 Kg",
    "Time": "6 Hrs",
    "Power": "1200 W",
    "Height": "752 mm",
    "Colors": "Cyan, Grey, White, Silver, Black",
    "Max_Power": "2000 W",
    "Warranty": "3 Year",
    "Length": "1500 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/144353/faast-f3-left-side-view.jpeg?isig=0&q=80"
  },
  {
    "Company": "Okaya",
    "Name": "ClassIQ 150+",
    "Price": "74,499 RS",
    "Range": "70 Km",
    "Speed": "25 Kmph",
    "Weight": "60 Kg",
    "Time": "5-6 Hrs",
    "Power": "250 W",
    "Height": "770 mm",
    "Colors": "Silver, Red, Black, Grey, Brown",
    "Max_Power": "250 W",
    "Warranty": "3 Year",
    "Length": "1930 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okaya-select-model-silver-1663137846660.jpg?q=80"
  },
  {
    "Company": "Evolet",
    "Name": "Polo",
    "Price": "49,699 RS",
    "Range": "90-120 Km",
    "Speed": "25Kmph",
    "Weight": "90Kg",
    "Time": "8-9 hrs",
    "Power": "250 W",
    "Height": "760 mm",
    "Colors": "White",
    "Max_Power": "350 W",
    "Warranty": "3 Year",
    "Length": "1850 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/evolet-select-model-white-1567601961070.jpg?q=80"
  },
  {
    "Company": "Pure EV",
    "Name": "EcoDryft",
    "Price": "1,14,999 RS",
    "Range": "130Km",
    "Speed": "75Kmph",
    "Weight": "101Kg",
    "Time": "6 hrs",
    "Power": "2,000 W",
    "Height": "760 mm",
    "Colors": "Black,Blue,Red,Silver",
    "Max_Power": "3,000 W",
    "Warranty": "3 Year",
    "Length": " 1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/1/versions/pureev-ecodryft-standard1679301076814.jpg?q=80"
  },
  {
    "Company": "Hero",
    "Name": "Photon HX",
    "Price": "1,10,376",
    "Range": "108 Km",
    "Speed": "45Kmph",
    "Weight": "87Kg",
    "Time": "5 hrs",
    "Power": "1,200 W",
    "Height": "790 mm",
    "Colors": "Blue,Mat Black,Beige",
    "Max_Power": "1,800 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/hero-electric-photon-hx20210511133422.jpg?q=80"
  },
  {
    "Company": "IVOOMi",
    "Name": "Jeet X Standard",
    "Price": "99,999Rs",
    "Range": "115 Km",
    "Speed": "70 Kmph",
    "Weight": "83.5Kg",
    "Time": "5 hrs",
    "Power": "1,800 W",
    "Height": "760 mm",
    "Colors": "Blue,Red,Grey,White",
    "Max_Power": "2500 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/131399/jeet-x-left-front-three-quarter.gif?isig=0&q=80"
  },
  {
    "Company": "Okinawa",
    "Name": "OKHI-90 Standard",
    "Price": "1,74,524 Rs",
    "Range": "160 Km",
    "Speed": "90 Kmph",
    "Weight": "88 Kg",
    "Time": "5-6 hrs",
    "Power": "2500 W",
    "Height": "803 mm",
    "Colors": "Blue,Red,Grey,White",
    "Max_Power": "3800 W",
    "Warranty": "3 year",
    "Length": "2200 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/114663/okhi-90-right-side-view-2.png?isig=0&q=80"
  },
  {
    "Company": "Hop Electric",
    "Name": "LYF Standard",
    "Price": "90,001 Rs",
    "Range": "80 km",
    "Speed": "25kmph",
    "Weight": "65kg",
    "Time": "3.30 hrs",
    "Power": "1200 W",
    "Height": "720 mm",
    "Colors": "Blue,Red,silver, White",
    "Max_Power": "2000 W",
    "Warranty": "3 year",
    "Length": "1850 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/130963/lyf-right-front-three-quarter-2.jpeg?isig=0&q=80"
  },
  {
    "Company": "Okinawa",
    "Name": "Lite Standard",
    "Price": "67,006 Rs",
    "Range": "60 km",
    "Speed": "25 kmph",
    "Weight": "80 Kg",
    "Time": "4-5 hrs",
    "Power": "250 W",
    "Height": "740 mm",
    "Colors": "Blue,Red,Cyan, White,Yellow",
    "Max_Power": "250 W",
    "Warranty": "3 year",
    "Length": "1730 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/okinawa-lite-standard20191107181833.jpg?q=80"
  },
  {
    "Company": "Okaya",
    "Name": "Faast F2B Standard",
    "Price": "99,950 Rs",
    "Range": "80 km",
    "Speed": "70 kmph",
    "Weight": "72 Kg",
    "Time": "5-6 hrs",
    "Power": "1200 W",
    "Height": "750 mm",
    "Colors": "grungy greeny,Boldly Black,Silver,Winter White,Catty Cyan,Groovy Grey",
    "Max_Power": "2000 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/132283/faast-f2b-left-front-three-quarter.gif?isig=0&q=80"
  },
  {
    "Company": "Odysse",
    "Name": "E2G0 Lead Acid",
    "Price": "59,750 Rs",
    "Range": "60 km",
    "Speed": "25 kmph",
    "Weight": "90 kg",
    "Time": "5 hrs",
    "Power": "250 W",
    "Height": "760 mm",
    "Colors": "Scarlet Red,Teal Green,Combat Blue,Matte Black,Black",
    "Max_Power": "250 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/odysse-e2go-lead-acid20210402183643.jpg?q=80"
  },
  {
    "Company": "Joy e-bike",
    "Name": "Monster Standard",
    "Price": "1,00,500 Rs",
    "Range": "75 km",
    "Speed": "25 kmph",
    "Weight": "93 kg",
    "Time": "4-4.5 hrs",
    "Power": "250 W",
    "Height": "750 mm",
    "Colors": "Black, Red",
    "Max_Power": "250 W",
    "Warranty": "3 year",
    "Length": "1460 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/joy-ebike-monster-standard20210106020700.jpg?q=80"
  },
  {
    "Company": "Benling",
    "Name": "Kriti Standard",
    "Price": "56,781 Rs",
    "Range": "60 Km",
    "Speed": "25 kmph",
    "Weight": "82 Kg",
    "Time": "8 hrs",
    "Power": "250 W",
    "Height": "790 mm",
    "Colors": "Matte Black,Shiny Red,Pure White",
    "Max_Power": "250 W",
    "Warranty": "3 year",
    "Length": "1775 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/benling-kriti-standard20201026203943.jpg?q=80"
  },
  {
    "Company": "Odysse",
    "Name": "Trot",
    "Price": "99,999 Rs",
    "Range": "75 km",
    "Speed": "25 kmph",
    "Weight": "110 kg",
    "Time": "4 hrs",
    "Power": "250 W",
    "Height": "750 mm",
    "Colors": "Maroon,Red,Black,Yellow",
    "Max_Power": "480 W",
    "Warranty": "3 year",
    "Length": "1820 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/141505/trot-left-front-three-quarter.jpeg?isig=0&q=80"
  },
  {
    "Company": "Gemopai",
    "Name": "Ryder Standar",
    "Price": "70,821 Rs",
    "Range": "90 km",
    "Speed": "25 kmph",
    "Weight": "80 kg",
    "Time": "3-4 hrs",
    "Power": "250 W",
    "Height": "760 mm",
    "Colors": "Imperial Red,Sapphire Blue,Charcoal Grey,Ivory Gold,Glossy White",
    "Max_Power": "400 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/bw/models/gemopai-ryder-standard20201006225821.jpg?q=80"
  },
  {
    "Company": "iVOOMi",
    "Name": "Eco Standard",
    "Price": "71,999 Rs",
    "Range": "80 km",
    "Speed": "25 kmph",
    "Weight": "60 kg",
    "Time": "4 hrs",
    "Power": "250 W",
    "Height": "770 mm",
    "Colors": "Red,Grey",
    "Max_Power": "450 W",
    "Warranty": "2 year",
    "Length": "1830 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/131389/eco-left-front-three-quarter.gif?isig=0&q=80"
  },
  {
    "Company": "Hero Electric",
    "Name": "Eddy",
    "Price": "72,142 Rs",
    "Range": "85 Km",
    "Speed": "25 kmph",
    "Weight": "75 Kg",
    "Time": "4-5 hrs",
    "Power": "250 W",
    "Height": "820 mm",
    "Colors": "Light Blue, Yellow",
    "Max_Power": "250 W",
    "Warranty": "3 year",
    "Length": "1920 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/hero-electric-select-model-light-blue-1654756313796.gif?q=80"
  },
  {
    "Company": "Techno Electra",
    "Name": "Emerge Standard",
    "Price": "68,286 Rs",
    "Range": "60-70 km",
    "Speed": "25 kmph",
    "Weight": "60 kg",
    "Time": "4-5 hrs",
    "Power": "250 W",
    "Height": "800 mm",
    "Colors": "Red,Yellow,Black",
    "Max_Power": "250 W",
    "Warranty": "2 year",
    "Length": "1930 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/undefined-black-1574424911295.jpg?q=80"
  },
  {
    "Company": "Odysee",
    "Name": "Hawk lite",
    "Price": "99,400 Rs",
    "Range": "85 Km",
    "Speed": "45 kmph",
    "Weight": "128 kg",
    "Time": "3.5 hrs",
    "Power": "1800 W",
    "Height": "830 mm",
    "Colors": "Charcoal Black,Gravity Grey,Intense Red,Mirage White,Blue",
    "Max_Power": "1900 W",
    "Warranty": "3 year",
    "Length": "1900 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/odysse-select-model-charcoal-black-1635507805541.jpg?q=80"
  },
  {
    "Company": "Okinawa",
    "Name": "Ridge 100 Standard",
    "Price": "1,14,716 Rs",
    "Range": "149 Km",
    "Speed": "50 kmph",
    "Weight": "85 Kg",
    "Time": "5-6 hrs",
    "Power": "800 W",
    "Height": "735 mm",
    "Colors": "Blue,Grey,Silver",
    "Max_Power": "1600 W",
    "Warranty": "3 year",
    "Length": "1740 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okinawa-select-model-blue-1689829757786.png?q=80"
  },
  {
    "Company": "Gemopai",
    "Name": "Ryder SuperMax Standard",
    "Price": "79,999 Rs",
    "Range": "100 Km",
    "Speed": "60 kmph",
    "Weight": "80 kg",
    "Time": "6 hrs",
    "Power": "1600 W",
    "Height": "750 mm",
    "Colors": "Electric Blue,Jazzy Neon,Graphite Grey,Blazing Red,Sparkling White,Fluorescent Yellow",
    "Max_Power": "2700 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/gemopai-select-model-electric-blue-1677670671196.jpg?q=80"
  },
  {
    "Company": "Okaya",
    "Name": "Faast F2T Standard",
    "Price": "99,400 Rs",
    "Range": "80 km",
    "Speed": "70 kmph",
    "Weight": "82 Kg",
    "Time": "5-6 hrs",
    "Power": "1200 W",
    "Height": "735 mm",
    "Colors": "GRUNGY GREENY,Boldly Black,Silver,Winter White,Catty Cyan,Groovy Grey",
    "Max_Power": "2000 W",
    "Warranty": "3 year",
    "Length": "1800 mm",
    "Touches": "No",
    "Image": "https://imgd.aeplcdn.com/1056x594/n/bw/models/colors/okaya-select-model-grungy-greeny-1669718118095.jpg?q=80"
  }
]
    
    for scooter in bike_data:
        scooter["Price"] = scooter["Price"].replace("Rs", "").replace("RS", "")
        
    if request.method == 'POST':
        form = BikeDetailForm(request.POST)
        if form.is_valid():
            # Get data from the form
            company = form.cleaned_data['company']
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            range = form.cleaned_data['range']
            speed = form.cleaned_data['speed']
            weight = form.cleaned_data['weight']
            height = form.cleaned_data['height']
            power = form.cleaned_data['power']
            colors = form.cleaned_data['colors']
            image = form.cleaned_data['image']
            warranty = form.cleaned_data['warranty']
            time = form.cleaned_data['time']
            max_power = form.cleaned_data['max_power']
            touches = form.cleaned_data['touches']
            # Add more fields as needed

            # Render a new HTML page with the data
            return render(request, 'bike_detail.html', {
                'company': company,
                'name': name,
                'price': price,
                'range': range,
                'speed': speed,
                'weight': weight,
                'height': height,
                'power': power,
                'colors': colors,
                'image': image,
                'warranty': warranty,
                'time': time,
                'max_power' : max_power,
                'touches' : touches
                
                # Add more data from the JSON or other sources
            })
    else:
        form = BikeDetailForm()
    return render(request, 'base.html', {'data': bike_data, 'form': form})